# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/16 19:01:02 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_strings
SRC_FILES	:=	ft_bcmp.c \
				ft_bcopy.c \
				ft_bzero.c \
				ft_ffs.c \
				ft_index.c \
				ft_rindex.c \
				ft_strcasecmp.c \
				ft_strncasecmp.c
include	../makeconfig
