# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/16 18:39:59 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_stdlib
SRC_FILES	:=	ft_abs.c \
				ft_labs.c \
				ft_llabs.c \
				ft_div.c \
				ft_ldiv.c \
				ft_lldiv.c \
				ft_itoa.c \
				ft_atoi.c \
				ft_atol.c \
				ft_atoll.c \
				ft_strtol.c \
				ft_strtoll.c \
				ft_strtoll_utils.c \
				ft_strtoul.c \
				ft_strtoull.c \
				ft_calloc.c
include		../makeconfig
