# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/16 18:22:34 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_ctype
SRC_FILES	:=	ft_isalnum.c \
				ft_isascii.c \
				ft_iscntrl.c \
				ft_isgraph.c \
				ft_isprint.c \
				ft_isspace.c \
				ft_isxdigit.c \
				ft_toupper.c \
				ft_isalpha.c \
				ft_isblank.c \
				ft_isdigit.c \
				ft_islower.c \
				ft_ispunct.c \
				ft_isupper.c \
				ft_tolower.c
include	../makeconfig
