# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/16 18:35:52 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
LIB_NAME	:=	ft_stdio
SRC_FILES	:=	ft_printf_utils/ft_utils.c \
				ft_printf_utils/ft_utils_strjoin.c \
				ft_printf_utils/ft_handle/ft_conv_info_handle.c \
				ft_printf_utils/ft_handle/ft_handle_char.c \
				ft_printf_utils/ft_handle/ft_handle_hex.c \
				ft_printf_utils/ft_handle/ft_handle_int.c \
				ft_printf_utils/ft_handle/ft_handle_int_u.c \
				ft_printf_utils/ft_handle/ft_handle_percentage.c \
				ft_printf_utils/ft_handle/ft_handle_ptr.c \
				ft_printf_utils/ft_handle/ft_handle_str.c \
				ft_printf_utils/ft_init/ft_conv_info_init.c \
				ft_printf_utils/ft_output/ft_conv_info_output.c \
				ft_printf_utils/ft_output/ft_output_char.c \
				ft_printf_utils/ft_output/ft_output_hex.c \
				ft_printf_utils/ft_output/ft_output_int.c \
				ft_printf_utils/ft_output/ft_output_percentage.c \
				ft_printf_utils/ft_output/ft_output_ptr.c \
				ft_printf_utils/ft_output/ft_output_str.c \
				ft_printf_utils/ft_output/ft_output_utils.c \
				ft_printf_utils/ft_set/ft_conv_info_set.c \
				ft_printf_utils/ft_set/ft_set_field_width.c \
				ft_printf_utils/ft_set/ft_set_flags.c \
				ft_printf_utils/ft_set/ft_set_precision.c \
				ft_printf_utils/ft_set/ft_set_specifier.c \
				ft_printf.c \
				ft_vprintf.c \
				ft_dprintf.c \
				ft_vdprintf.c \
				ft_getc.c \
				ft_getchar.c \
				ft_fgetc.c \
				ft_fwrite.c \
				ft_putchar.c \
				ft_fflush.c \
				ft_read.c \
				ft_write.c
include	../makeconfig
