name: Norminette

on:
  pull_request:
    branches: [ master, develop ]
    paths:
      - "src/**"
      - "includes/**"
      - ".github/workflows/norminette.yml"
  push:
    branches: [ master, develop ]
    paths:
      - "src/**"
      - "includes/**"

jobs:
  lint:
    name: norminette
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Norminette
        run: |
          pip install --upgrade pip
          # バージョン固定したい場合は "norminette==3.3.61" のように固定
          pip install norminette==3.3.61

      - name: Run Norminette
        run: |
          # 余計なディレクトリが混ざらないよう明示的に指定
          norminette src includes
