name: Strip-merge PR into master

on:
  pull_request:
    branches: [ master ]
    types: [ labeled, synchronize, reopened, opened ]
  workflow_dispatch:

permissions:
  contents: write        # master へ push するため
  pull-requests: write   # コメントやCloseに使う場合

env:
  # ここに master に入れたくないパスを列挙（スペース区切り）
  EXCLUDE_PATHS: ".github .vscode docs .gitlab-ci.yml"

jobs:
  strip_merge:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       contains(join(github.event.pull_request.labels.*.name, ','), 'strip-merge'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          # PRヘッドをまず取得（イベントで開かれたリビジョン）
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Configure Git user
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Switch to master & fast-forward
        run: |
          git switch master
          git pull --ff-only origin master

      - name: Determine source branch
        id: src
        run: |
          # PRイベントならPRのヘッドブランチ、手動実行なら develop
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "pr=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "branch=develop" >> $GITHUB_OUTPUT
            echo "pr=" >> $GITHUB_OUTPUT
          fi

      - name: Merge (no-commit, no-ff)
        run: |
          git merge --no-commit --no-ff origin/${{ steps.src.outputs.branch }}

      - name: Strip excluded paths from merge result
        run: |
          for p in $EXCLUDE_PATHS; do
            # マージ結果から “HEAD(=master直前) の状態” に戻す = 取り込まない
            git restore --staged --worktree --source=HEAD -- $p 2>/dev/null || true
          done

      - name: Commit and push to master
        run: |
          git commit -m "Strip-merge '${{ steps.src.outputs.branch }}' into master (exclude: $EXCLUDE_PATHS)" || echo "Nothing to commit"
          # 変更が無ければスキップ
          if git diff --quiet origin/master..HEAD; then
            echo "No changes to push."
          else
            git push origin master
          fi

      - name: Comment & optionally close PR
        if: ${{ steps.src.outputs.pr != '' }}
        env:
          PR_NUMBER: ${{ steps.src.outputs.pr }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "$PR_NUMBER" -b "✅ Strip-merge completed: excluded paths were not applied to \`master\`."
          # 自動でCloseしたいなら以下を有効化
          # gh pr close "$PR_NUMBER" --delete-branch=false
